namespace Tutorial
{
	public enum eExecKind
	{
		ADV = 0,
		WindowInfo = 1,
		WindowData = 2,
		Button = 3,
		Popup = 4,
		Wait = 5,
		FairyAppear = 6,
		FairyMove = 7,
		FairyMove2 = 8,
		FairyMove3 = 9,
		FariyWait = 10,
		FairyPick = 11,
		FairyRotate = 12,
		FairyRotate2 = 13,
		FairyRotate3 = 14,
		FairyBanish = 15,
		FairySpotLight = 16,
		WaitTouch = 17,
		WaitApproachFairy = 18,
		WaitApproachObject = 19,
		CameraTarget = 20,
		CameraFov = 21,
		Arrow = 22,
		OpenQuestBoard = 23,
		CameraSpeed = 24,
		WaitQuestBoard = 25,
		PopEnemy = 26,
		FairyMoveObj = 27,
		FairyEmote = 28,
		FairyEffect = 29,
		CloseLauncher = 30,
		ClickButton = 31,
		OpenLauncher = 32,
		JumpRequest = 33,
		QuestClear = 34,
		FadeWait = 35,
		CloseUI = 36,
		DispGuide = 37,
		TargetArrow = 38,
		TargetArrowOFF = 39,
		ButtonStatus = 40,
		SkipSelect = 41,
		OnSkip = 42,
		QstTgtActive = 43,
		QstTgtInfo = 44,
		WaitNoticce = 45,
		LoginBonus = 46,
		EnumMax = 47
	}
}
