public enum EBattleVoiceID
{
	eBATTLENORMALATTACK = 0,
	eBATTLECRITICALATTACK = 1,
	eBATTLECHANCE = 2,
	eBATTLENORMALDAMAGE = 3,
	eBATTLEBIGDMAGE = 4,
	eBATTLEDEAD = 5,
	eBATTLE2CHAIN = 6,
	eBATTLE3CHAIN = 7,
	eBATTLESKILL = 8,
	eBATTLEUNI = 9,
	eBATTLERECOVER = 10,
	eBATTLESTART = 11,
	eBATTLEJOIN = 12,
	eBATTLEVICTORY = 13,
	eBATTLEITEMUSE = 14,
	eBATTLEATTACKSKILL = 15,
	eBATTLESUPPORTSKILL = 16,
	eBATTLESTART2 = 17,
	eBATTLESMALLAPPEAL = 18,
	eBATTLELERGEAPPEAL = 19,
	eBATTLESPECIALSKILL = 20
}
