public enum EBattleScoreKind
{
	eNONE = 0,
	eBOSS_WIN = 1,
	eTOTAL_DAMAGE = 2,
	eBIG_DAMAGE = 3,
	eUNDER_MOVE = 4,
	eWEAK_ATACK = 5,
	eCRITICAL_ATACK = 6,
	eUSE_CHAR = 7,
	eUSE_ITEM = 8,
	eSKILL_FINISH = 9,
	eITEM_FINISH = 10,
	eALL_CHAR_SURVIVAL = 11,
	eSKILL_CHAIN = 12,
	eCHAR_DEAD = 13,
	eOVER_MOVE = 14,
	eANNIHILATION = 15,
	eSLIP_POISON = 16,
	eSLIP_BURN = 17,
	eSLIP_FROZEN = 18
}
