public enum ESystemVoiceID
{
	eLEVELUP = 0,
	eLIMITBREAK = 1,
	eSKILLGET = 2,
	ePOWERUP = 3,
	eQUESTBOARD = 4,
	eQUEST_CLEAR = 5,
	eALTER_COMPLETE = 6,
	eALTER_SUCCESS = 7,
	eRECIPE_DISCOVERY = 8,
	eINTRODUCTION = 9,
	eGREETING = 10,
	eNICE_MEET_YOU = 11,
	eGOODBY = 12,
	eDO_OUT_BEST = 13,
	eREADER = 14,
	eTARU = 15,
	eACADEMY = 16,
	eGET_RARE = 17
}
